management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true

logging:
    level:
        com:
            yuns: DEBUG
server:
    port: 9000